"""Unit tests for TraceContextMiddleware and correlation-id helpers.

Gate 5 coverage (per Phase 1 specification):
  (a) X-Correlation-ID header passthrough — supplied id is echoed back
  (b) Auto-generation when header is missing — UUID4 injected
  (c) structlog binding visible in JSON log record — correlation_id key present
  (d) Nested async task inherits the contextvar value

All tests are self-contained: they spin up an in-process ASGI app using
httpx.AsyncClient with no network I/O.
"""

from __future__ import annotations

import asyncio
import json
import uuid

import pytest
import structlog
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient

from omnitrade.observability.trace_context import (
    TraceContextMiddleware,
    configure_structlog,
    get_correlation_id,
)

# ── helpers ─────────────────────────────────────────────────────────────── #


def _make_app() -> FastAPI:
    """Build a minimal FastAPI app with TraceContextMiddleware for testing."""
    app = FastAPI()
    app.add_middleware(TraceContextMiddleware)

    @app.get("/echo")
    async def echo() -> dict[str, str]:
        return {"correlation_id": get_correlation_id()}

    return app


# ── (a) header passthrough ────────────────────────────────────────────────── #


@pytest.mark.asyncio
async def test_correlation_id_passthrough() -> None:
    """Supplied X-Correlation-ID is echoed in response header and body."""
    supplied_id = "test-corr-id-12345"
    app = _make_app()

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        response = await client.get("/echo", headers={"X-Correlation-ID": supplied_id})

    assert response.status_code == 200
    assert response.headers["X-Correlation-ID"] == supplied_id
    assert response.json()["correlation_id"] == supplied_id


# ── (b) auto-generation when header is missing ────────────────────────────── #


@pytest.mark.asyncio
async def test_correlation_id_autogenerated() -> None:
    """X-Correlation-ID is auto-generated as a UUID4 when not supplied."""
    app = _make_app()

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        response = await client.get("/echo")

    assert response.status_code == 200
    cid = response.headers.get("X-Correlation-ID", "")
    assert cid != "", "response must carry X-Correlation-ID header"

    # Must be a valid UUID4
    parsed = uuid.UUID(cid)
    assert parsed.version == 4

    # Body and header agree
    assert response.json()["correlation_id"] == cid


@pytest.mark.asyncio
async def test_correlation_id_unique_per_request() -> None:
    """Two requests without supplied id receive different correlation ids."""
    app = _make_app()

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        r1 = await client.get("/echo")
        r2 = await client.get("/echo")

    cid1 = r1.headers["X-Correlation-ID"]
    cid2 = r2.headers["X-Correlation-ID"]
    assert cid1 != cid2


# ── (c) structlog binding visible in JSON log record ─────────────────────── #


@pytest.mark.asyncio
async def test_structlog_binding_in_log_record() -> None:
    """correlation_id appears in structlog JSON output during a request."""
    captured: list[str] = []

    class CapturingLogger:
        def msg(self, message: str) -> None:
            captured.append(message)

        info = msg
        warning = msg
        error = msg

    class CapturingLoggerFactory:
        def __call__(self, *args: object) -> CapturingLogger:
            return CapturingLogger()

    # Reconfigure structlog to capture output
    structlog.configure(
        processors=[
            structlog.contextvars.merge_contextvars,
            structlog.processors.add_log_level,
            structlog.processors.JSONRenderer(),
        ],
        logger_factory=CapturingLoggerFactory(),
        cache_logger_on_first_use=False,
    )

    supplied_id = "structlog-test-999"

    _app = FastAPI()
    _app.add_middleware(TraceContextMiddleware)

    @_app.get("/log-test")
    async def log_and_return() -> dict[str, str]:
        log = structlog.get_logger()
        log.info("test_event", extra_field="hello")
        return {"ok": "1"}

    async with AsyncClient(transport=ASGITransport(app=_app), base_url="http://test") as client:
        await client.get("/log-test", headers={"X-Correlation-ID": supplied_id})

    assert len(captured) >= 1, "expected at least one log record"
    record = json.loads(captured[0])
    assert record.get("correlation_id") == supplied_id, (
        f"correlation_id not found in log record: {record}"
    )

    # Restore default structlog config for remaining tests
    configure_structlog()


# ── (d) nested async task inherits the contextvar value ──────────────────── #


@pytest.mark.asyncio
async def test_contextvar_inherited_by_nested_async_task() -> None:
    """ContextVar value is visible inside asyncio.create_task() children."""
    supplied_id = "inherited-corr-id-xyz"
    inherited_ids: list[str] = []

    _app = FastAPI()
    _app.add_middleware(TraceContextMiddleware)

    @_app.get("/nested")
    async def nested_task_endpoint() -> dict[str, str]:
        async def child() -> None:
            # asyncio tasks inherit a *copy* of the context at creation time
            inherited_ids.append(get_correlation_id())

        task = asyncio.create_task(child())
        await task
        return {"ok": "1"}

    async with AsyncClient(transport=ASGITransport(app=_app), base_url="http://test") as client:
        await client.get("/nested", headers={"X-Correlation-ID": supplied_id})

    assert len(inherited_ids) == 1
    assert inherited_ids[0] == supplied_id, (
        f"nested task saw '{inherited_ids[0]}', expected '{supplied_id}'"
    )
