"""add justification and correlation_id columns to agent_decisions

Revision ID: 0005
Revises: 0004
Create Date: 2026-04-19

Closes two gaps identified by the FE↔BE contract audit:

* ``justification`` — StructuredReason's full chain-of-thought (Step 0
  observed mean ≈ 1385 chars) was generated by think_node but never
  persisted; only a derivative substring leaked into ``actions_taken``.
  Add a dedicated nullable TEXT column so /api/v1/decisions can surface
  the raw CoT to the UI.

* ``correlation_id`` — ``AgentDecision.correlation_id`` existed in the
  domain / API / UI layers but had no DB column, so
  DecisionRepository.list_recent always returned empty strings after
  reload. Add a NOT NULL TEXT column with ``''`` default (parity with
  the domain field default) plus an index for tracing lookups.

Non-destructive: both columns are backfillable — existing rows get the
defaults and continue to serialise normally.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("agent_decisions") as batch_op:
        batch_op.add_column(sa.Column("justification", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "correlation_id",
                sa.Text(),
                nullable=False,
                server_default="",
            )
        )
    op.create_index(
        "idx_decisions_correlation_id",
        "agent_decisions",
        ["correlation_id"],
    )


def downgrade() -> None:
    op.drop_index("idx_decisions_correlation_id", table_name="agent_decisions")
    with op.batch_alter_table("agent_decisions") as batch_op:
        batch_op.drop_column("correlation_id")
        batch_op.drop_column("justification")
